DATASET:
    NAME: "ade20k"
    MEAN: [0.5, 0.5, 0.5]
    STD: [0.5, 0.5, 0.5]
    MODE: 'val'
TRAIN:
    EPOCHS: 120
    BATCH_SIZE: 8
    CROP_SIZE: 480
    BASE_SIZE: 520
TEST:
    BATCH_SIZE: 8

SOLVER:
    LR: 0.01

MODEL:
    MODEL_NAME: "DeepLabV3_Plus"
    BACKBONE: "xception65"
    BN_EPS_FOR_ENCODER: 1e-3
