DATASET:
    NAME: "cityscape"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 500
    BATCH_SIZE: 16
    CROP_SIZE: 1024
TEST:
    BATCH_SIZE: 8

SOLVER:
    LR: 0.02
    WEIGHT_DECAY: 5e-4

MODEL:
    MODEL_NAME: "HardNet"

