DATASET:
    NAME: "cityscape"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 400
    BATCH_SIZE: 4
    CROP_SIZE: 768
TEST:
    BATCH_SIZE: 4
    CROP_SIZE: (1024, 2048)

SOLVER:
    LR: 0.02

MODEL:
    MODEL_NAME: "DFANet"
    BACKBONE: "xception_a"

