DATASET:
    NAME: "cityscape"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 400
    BATCH_SIZE: 2
    CROP_SIZE: 512
TEST:
    BATCH_SIZE: 2
    CROP_SIZE: (1024, 2048)
#    TEST_MODEL_PATH: trained_models/deeplabv3_plus_resnet101_segmentron.pth

SOLVER:
    LR: 0.001

MODEL:
    MODEL_NAME: "UNet"

