DATASET:
    NAME: "cityscape"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 400
    BATCH_SIZE: 8
    CROP_SIZE: 769

TEST:
    BATCH_SIZE: 8
    CROP_SIZE: (1025, 2049)

SOLVER:
    LR: 0.02

MODEL:
    MODEL_NAME: "DeepLabV3_Plus"
    BACKBONE: "mobilenet_v2"
    OUTPUT_STRIDE: 16
    DEEPLABV3_PLUS:
        USE_ASPP: False
        ENABLE_DECODER: False

