DATASET:
    NAME: "cityscape"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 400
    BATCH_SIZE: 4
    CROP_SIZE: 769
TEST:
    BATCH_SIZE: 4
    CROP_SIZE: (1025, 2049)
    TEST_MODEL_PATH: /home/yoo/workspace/SegmenTron/runs/checkpoints/DeepLabV3_Plus_resnet50_cityscape_2021-04-02-14-03/best_model.pth
    # TEST_MODEL_PATH: /home/yoo/Downloads/deeplabv3_plus_resnet101_segmentron.pth
    
SOLVER:
    LR: 0.02

MODEL:
    MODEL_NAME: "DeepLabV3_Plus"
    BACKBONE: "resnet50"
    # BACKBONE: "resnet50"

