DATASET:
  NAME: "gta"
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  # MEAN: [0, 0, 0]
  # STD: [0, 0, 0]
TRAIN:
  EPOCHS: 400
  BATCH_SIZE: 4
  CROP_SIZE: 769
TEST:
  BATCH_SIZE: 4
  # CROP_SIZE: (1053, 1915)
  CROP_SIZE: (640, 360)
#    TEST_MODEL_PATH: trained_models/deeplabv3_plus_resnet101_segmentron.pth

SOLVER:
  LR: 0.02

MODEL:
  MODEL_NAME: "DeepLabV3_Plus"
  # BACKBONE: "resnet50"
  BACKBONE: "resnet101"
